public class Main {
    public static void main(String[] args) {
        System.out.println("Задание 1");
        int a = 147;
        System.out.println("Значение переменной с типом int = " + a);
        byte b = 35;
        System.out.println("Значение переменной с типом byte = " + b);
        short c = -31;
        System.out.println("Значение переменной с типом short = " + c);
        long d = 90000000000L;
        System.out.println("Значение переменной с типом long = " + d);
        float e = 3.22f;
        System.out.println("Значение переменной с типом float = " + e);
        double f = 3.1526866425;
        System.out.println("Значение переменной с типом double = " + f);
        System.out.println("Задание 2");
        float g = 27.12F;
        long h = 987678965549L;
        float j = 2.786F;
        short k = 569;
        short l = -159;
        short m = 27897;
        byte n = 67;
        System.out.println("Задание 3");
        byte quantityOfPupils1 = 23;
        byte quantityOfPupils2 = 27;
        byte quantityOfPupils3 = 30;
        short totalNumberOfSheets = 480;
        short totalNumberOfStudents = (short) (quantityOfPupils1 + quantityOfPupils2 + quantityOfPupils3);
        short numberOfSheetsPerStudent = (short) (totalNumberOfSheets / totalNumberOfStudents);
        System.out.println("На каждого ученика расчитано " + numberOfSheetsPerStudent + " листов бумаги");
        System.out.println("Задание 4");
        byte numberOfBottles1 = 16;
        byte numberOfMinutes1 = 2;
        int machinePerformance1 = numberOfBottles1 / numberOfMinutes1; //Рассчитали сколько она производить за одну минуту
        byte numberOfMinutes2 = 20;
        int machinePerformance2 = (machinePerformance1 * numberOfMinutes2);
        System.out.println("За 20 минут машина произвела " + machinePerformance2 + " штук бутылок");
        int numberOfMinutes3 = 60 * 24;
        int machinePerformance3 = (machinePerformance1 * numberOfMinutes3);
        System.out.println("За сутки машина произвела " + machinePerformance3 + " штук бутылок");
        int numberOfMinutes4 = numberOfMinutes3 * 3;
        int machinePerformance4 = (machinePerformance1 * numberOfMinutes4);
        System.out.println("За 3 дня машина произвела " + machinePerformance4 + " штук бутылок");
        int numberOfMinutes5 = numberOfMinutes3 * 30;
        int machinePerformance5 = (machinePerformance1 * numberOfMinutes5);
        System.out.println("За месяц машина произвела " + machinePerformance5 + " штук бутылок");
        System.out.println("Задание 5");
        byte totalNumberOfCans = 120;
        byte numberOfCansOfWhitePaintPerClass = 2;
        byte numberOfCansOfBrownPaintPerClass = 4;
        int totalNumberOfCansPerClass = numberOfCansOfWhitePaintPerClass + numberOfCansOfBrownPaintPerClass;
        int numberOfClasses = totalNumberOfCans / totalNumberOfCansPerClass;
        int numberOfCansOfWhitePaint = numberOfClasses * numberOfCansOfWhitePaintPerClass;
        int numberOfCansOfBrownPaint = numberOfClasses * numberOfCansOfBrownPaintPerClass;
        System.out.println("В школе, где  " + numberOfClasses + " классов, нужно " + numberOfCansOfWhitePaint + " банок белой краски и " + numberOfCansOfBrownPaint + " банок коричневой краски");
        System.out.println("Задание 6");
        byte numberOfBananas = 5;
        byte weightOfOneBanana = 80;
        int totalWeightOfBananas = numberOfBananas * weightOfOneBanana;
        byte numberOfServingsOfMilk = 2;
        int theWeightOfOneServingOfMilk = 105;
        int totalMilkWeight = numberOfServingsOfMilk * theWeightOfOneServingOfMilk;
        byte theAmountOfIceCream = 2;
        byte theWeightOfOneIceCreamBriquette = 100;
        int totalWeightOfIceCream = theAmountOfIceCream * theWeightOfOneIceCreamBriquette;
        byte numberOfEggs = 4;
        byte weightOfOneEgg = 70;
        int totalWeightOfEggs = numberOfEggs * weightOfOneEgg;
        int totalWeightOfAllProducts = totalWeightOfBananas + totalMilkWeight + totalWeightOfIceCream + totalWeightOfEggs; //общий вес продуктов в граммах
        double totalWeightOfAllProducts2 = totalWeightOfAllProducts / 1000.0;
        System.out.println("Общий вес такого завтрака " + totalWeightOfAllProducts + " грамм, что равно " + totalWeightOfAllProducts2 + " килограмм");
        System.out.println("Задание 7");
        byte theRequiredNumberOfKilograms = 7;
        int requiredNumberOfGrams = theRequiredNumberOfKilograms * 1000;
        short numberOfGrams1 = 250;
        int numberOfDays1 = requiredNumberOfGrams / numberOfGrams1;
        System.out.println("Если спортсмен будет сбрасывать каждый день по 250 гр, то ему потребуется " + numberOfDays1 + " дней, чтобы достичь нужного веса");
        short numberOfGrams2 = 500;
        int numberOfDays2 = requiredNumberOfGrams / numberOfGrams2;
        System.out.println("Если спортсмен будет сбрасывать каждый день по 500 гр, то ему потребуется " + numberOfDays2 + " дней, чтобы достичь нужного веса");
        int averageNumberOfDays = (numberOfDays1 + numberOfDays2) / 2;
        System.out.println("В среднем это " + averageNumberOfDays + " день");
        System.out.println("Задание 8");
        int salaryOfMasha1 = 67760;
        int salaryOfDenis1 = 83690;
        double salaryOfKristina1 = 76230;
        double salaryOfMasha2 = salaryOfMasha1 * 1.1;
        double salaryOfDenis2 = salaryOfDenis1 * 1.1;
        double salaryOfKristina2 = salaryOfKristina1 * 1.1;
        int annualIncomeOfMasha1 = salaryOfMasha1 * 12;
        double annualIncomeOfMasha2 = salaryOfMasha2*12;
        double theDifferenceInAnnualIncomeOfMasha = annualIncomeOfMasha2 - annualIncomeOfMasha1;
        System.out.println("Маша теперь получает " + salaryOfMasha2 + " рублей в месяц. Годовой доход вырос на " + theDifferenceInAnnualIncomeOfMasha + " рублей");
        int annualIncomeOfDenis1 = salaryOfDenis1*12;
        double annualIncomeOfDenis2 = salaryOfDenis2*12;
        double theDifferenceInAnnualIncomeOfDenis = annualIncomeOfDenis2-annualIncomeOfDenis1;
        System.out.println("Денис теперь получает " + salaryOfDenis2 + " рублей в месяц. Годовой доход вырос на " + theDifferenceInAnnualIncomeOfDenis + " рублей");
        double annualIncomeOfKristina1 = salaryOfKristina1*12;
        double annualIncomeOfKristina2 = salaryOfKristina2*12;
        double theDifferenceInAnnualIncomeOfKristina = annualIncomeOfKristina2-annualIncomeOfKristina1;
        System.out.println("Кристина теперь получает " + salaryOfKristina2 + " рублей в месяц. Годовой доход вырос на " + theDifferenceInAnnualIncomeOfKristina + " рублей");
    }
}